"""Bringing the access point up and tearing it back down.

Design notes
------------
*Virtual interface.*  The AP lives on its own ``__ap`` interface cloned from
the radio, the way ``create_ap`` does it.  NetworkManager's own hotspot takes
the physical device over instead, which drops the very connection you meant
to share.

*Config placement.*  The generated hostapd config goes wherever the active
MAC policy permits (see :mod:`hotspotd.confine`), not to a temp directory.

*Supervision.*  hostapd runs as a transient systemd unit rather than a
forked background process, so it gets a cgroup, restarts under policy and
survives the CLI exiting.  ``journalctl -u hotspotd-hostapd`` then just works.

*NAT.*  firewalld is driven through ``firewall-cmd`` when it is running, so
we never fight the active backend; otherwise we fall back to nftables.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass

HOSTAPD_UNIT = "hotspotd-hostapd"
DNSMASQ_PID = "/run/hotspotd-dnsmasq.pid"


class BackendError(RuntimeError):
    pass


def run(*cmd: str, check: bool = True, quiet: bool = False) -> subprocess.CompletedProcess:
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if check and proc.returncode != 0:
        detail = (proc.stderr or proc.stdout).strip()
        raise BackendError(f"{' '.join(cmd)}: {detail}")
    if not quiet and proc.returncode != 0:
        pass
    return proc


@dataclass
class ApConfig:
    ssid: str
    passphrase: str
    channel: int
    hw_mode: str
    ap_iface: str = "ap0"
    wifi_iface: str = "wlo1"
    uplink: str = ""
    subnet: str = "192.168.12"
    hidden: bool = False
    config_path: str = "/etc/hostapd.hotspotd.conf"

    def validate(self) -> None:
        if not 8 <= len(self.passphrase) <= 63:
            raise BackendError("WPA2 passphrase must be 8-63 characters")
        if not 1 <= len(self.ssid) <= 32:
            raise BackendError("SSID must be 1-32 characters")


def render_hostapd(cfg: ApConfig) -> str:
    return "\n".join(
        [
            "# generated by hotspotd - do not edit, it is rewritten on every start",
            f"interface={cfg.ap_iface}",
            "driver=nl80211",
            f"ssid={cfg.ssid}",
            f"hw_mode={cfg.hw_mode}",
            f"channel={cfg.channel}",
            "auth_algs=1",
            f"ignore_broadcast_ssid={1 if cfg.hidden else 0}",
            "wpa=2",
            f"wpa_passphrase={cfg.passphrase}",
            "wpa_key_mgmt=WPA-PSK",
            "rsn_pairwise=CCMP",
            "",
        ]
    )


def write_config(cfg: ApConfig) -> None:
    directory = os.path.dirname(cfg.config_path)
    os.makedirs(directory, exist_ok=True)
    old = os.umask(0o077)          # the passphrase is in here
    try:
        with open(cfg.config_path, "w") as fh:
            fh.write(render_hostapd(cfg))
    finally:
        os.umask(old)


def create_ap_interface(cfg: ApConfig) -> None:
    run("iw", "dev", cfg.ap_iface, "del", check=False)
    run("iw", "dev", cfg.wifi_iface, "interface", "add", cfg.ap_iface, "type", "__ap")
    run("ip", "link", "set", cfg.ap_iface, "up")
    if shutil.which("nmcli"):
        run("nmcli", "dev", "set", cfg.ap_iface, "managed", "no", check=False)


def configure_network(cfg: ApConfig) -> None:
    run("ip", "addr", "flush", "dev", cfg.ap_iface, check=False)
    run("ip", "addr", "add", f"{cfg.subnet}.1/24", "dev", cfg.ap_iface)
    run("sysctl", "-qw", "net.ipv4.ip_forward=1")
    _nat_up(cfg)


def _firewalld_running() -> bool:
    if not shutil.which("firewall-cmd"):
        return False
    return run("firewall-cmd", "--state", check=False).returncode == 0


def _nat_up(cfg: ApConfig) -> None:
    if _firewalld_running():
        run("firewall-cmd", "-q", "--zone=trusted", f"--add-interface={cfg.ap_iface}", check=False)
        run("firewall-cmd", "-q", "--zone=public", "--add-masquerade", check=False)
        return
    if shutil.which("nft"):
        run("nft", "add", "table", "ip", "hotspotd", check=False)
        run("nft", "add", "chain", "ip", "hotspotd", "post",
            "{ type nat hook postrouting priority 100 ; }", check=False)
        run("nft", "add", "rule", "ip", "hotspotd", "post",
            "ip", "saddr", f"{cfg.subnet}.0/24", "oifname", cfg.uplink or "!=", "masquerade",
            check=False)
        return
    raise BackendError("neither firewalld nor nft available for NAT")


def _nat_down(cfg: ApConfig) -> None:
    if _firewalld_running():
        run("firewall-cmd", "-q", "--zone=trusted", f"--remove-interface={cfg.ap_iface}", check=False)
        run("firewall-cmd", "-q", "--zone=public", "--remove-masquerade", check=False)
    elif shutil.which("nft"):
        run("nft", "delete", "table", "ip", "hotspotd", check=False)


def start_dnsmasq(cfg: ApConfig) -> None:
    run(
        "dnsmasq",
        f"--pid-file={DNSMASQ_PID}",
        f"--interface={cfg.ap_iface}",
        "--bind-interfaces",
        f"--dhcp-range={cfg.subnet}.10,{cfg.subnet}.200,12h",
        f"--dhcp-option=3,{cfg.subnet}.1",
        f"--dhcp-option=6,{cfg.subnet}.1",
        "--except-interface=lo",
        f"--listen-address={cfg.subnet}.1",
    )


def start_hostapd(cfg: ApConfig) -> None:
    run("systemd-run", f"--unit={HOSTAPD_UNIT}", "--quiet",
        "--property=Restart=no", "/usr/sbin/hostapd", cfg.config_path)


def hostapd_active() -> bool:
    return run("systemctl", "is-active", "--quiet", HOSTAPD_UNIT, check=False).returncode == 0


def hostapd_log(lines: int = 20) -> str:
    return run("journalctl", "-u", HOSTAPD_UNIT, "-n", str(lines),
               "--no-pager", check=False).stdout


def teardown(cfg: ApConfig) -> None:
    run("systemctl", "stop", HOSTAPD_UNIT, check=False)
    run("systemctl", "reset-failed", HOSTAPD_UNIT, check=False)
    try:
        with open(DNSMASQ_PID) as fh:
            os.kill(int(fh.read().strip()), 15)
    except (OSError, ValueError):
        pass
    try:
        os.unlink(DNSMASQ_PID)
    except OSError:
        pass
    _nat_down(cfg)
    run("iw", "dev", cfg.ap_iface, "del", check=False)
    try:
        os.unlink(cfg.config_path)
    except OSError:
        pass


def clients(cfg: ApConfig) -> list[str]:
    out = run("ip", "neigh", "show", "dev", cfg.ap_iface, check=False).stdout
    return [l for l in out.splitlines() if l.strip() and "FAILED" not in l]
